apiVersion: v1
kind: Secret
metadata:
  name: os-pkg-update
  namespace: cattle-system
type: Opaque
stringData:
  update.sh: |
    #!/bin/sh

    UPDATE_SERVICE_PATH=/etc/systemd/system/edge-update.service
    
    echo "Creating edge-update.service..."
    cat <<'EOF' >${UPDATE_SERVICE_PATH}
    [Unit]
    Description=SUSE Edge Upgrade Service
    ConditionACPower=true
    Wants=network.target
    After=network.target

    [Service]
    Type=oneshot
    Environment=UPDATE_METHOD=dup
    EnvironmentFile=-/etc/edge/edge-update.conf
    ExecStart=/usr/sbin/transactional-update cleanup ${UPDATE_METHOD}
    ExecStartPost=-/bin/bash -c '[ -f /run/reboot-needed ] && shutdown -r +1'
    IOSchedulingClass=best-effort
    IOSchedulingPriority=7
    EOF

    echo "Starting OS package update process..."
    systemctl start edge-update.service &
    tail --pid $! -f cat /var/log/transactional-update.log

    echo "Cleaning up..."
    # Remove service after it has finished its work
    rm ${UPDATE_SERVICE_PATH}
    systemctl daemon-reload
