# SUC Plan related to upgrading the K3s version of worker nodes
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-upgrade-worker
  labels:
    k3s-upgrade: worker
spec:
  concurrency: 2 
  nodeSelector:
    matchExpressions:
      # will trigger upgrade for any node that does not contain the 'node-role.kubernetes.io/control-plane' label
      - {key: node-role.kubernetes.io/control-plane, operator: NotIn, values: ["true"]}
  serviceAccountName: system-upgrade-controller
  prepare:
    image: rancher/k3s-upgrade
    args:
    - prepare
    - k3s-upgrade-control-plane
  cordon: true
  upgrade:
    image: rancher/k3s-upgrade
  version: v1.31.2+k3s1
