apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: cp-os-upgrade-edge-310
spec:
  concurrency: 1
  # Override the default SUC set value of 900 with something that will
  # give the enough time to the control-plane plan to finish 
  jobActiveDeadlineSecs: 43200
  nodeSelector:
    matchExpressions:
      # will trigger upgrade for any node containing the 'node-role.kubernetes.io/control-plane' label
      - {key: node-role.kubernetes.io/control-plane, operator: In, values: ["true"]}
  tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Equal"
    value: "true"
    effect: "NoExecute"
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Equal"
    effect: "NoSchedule"
  - key: "node-role.kubernetes.io/etcd"
    operator: "Equal"
    effect: "NoExecute"
  serviceAccountName: system-upgrade-controller
  secrets:
    - name: os-upgrade-edge-310
      path: /host/run/system-upgrade/secrets/os-upgrade-edge-310
  cordon: true
  version: "3.1.0"
  upgrade:
    image: registry.suse.com/bci/bci-base:15.6
    command: ["chroot", "/host"]
    args: ["sh", "/run/system-upgrade/secrets/os-upgrade-edge-310/upgrade.sh"]
    envFrom:
    - configMapRef:
        name: os-upgrade-edge-310
