# SUC Plan related to upgrading the RKE2 version of worker nodes
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: rke2-upgrade-worker
  labels:
    rke2-upgrade: worker
spec:
  concurrency: 2
  nodeSelector:
    matchExpressions:
      # will trigger upgrade for any node that does not contain the 'node-role.kubernetes.io/control-plane' label
      - {key: node-role.kubernetes.io/control-plane, operator: NotIn, values: ["true"]}
  prepare:
    args:
    - prepare
    - rke2-upgrade-control-plane
    image: rancher/rke2-upgrade
  serviceAccountName: system-upgrade-controller
  cordon: true
  drain:
    force: true
  upgrade:
    image: rancher/rke2-upgrade
  version: v1.31.7+rke2r1
