apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: eib-chart-migration-prep
spec:
  concurrency: 3
  nodeSelector:
    matchExpressions:
      # Run on all control-plane nodes
      - {key: node-role.kubernetes.io/control-plane, operator: In, values: ["true"]}
  tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Equal"
    value: "true"
    effect: "NoExecute"
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Equal"
    effect: "NoSchedule"
  - key: "node-role.kubernetes.io/etcd"
    operator: "Equal"
    effect: "NoExecute"
  serviceAccountName: system-upgrade-controller
  secrets:
    - name: migration-prep-script
      path: /host/run/system-upgrade/secrets/migration-prep-script
  cordon: false
  # Version of the specific Edge release that this Plan relates to
  version: "3.1.2"
  upgrade:
    image: registry.suse.com/edge/3.1/kubectl:1.30.3
    command: ["/bin/sh", "/host/run/system-upgrade/secrets/migration-prep-script/prepare_chart_migration.sh"]
    # For when you want to backup your chart
    # manifest data under a specific directory
    # 
    # envs:
    # - name: MANIFEST_BACKUP_DIR
    #   value: "/foo/bar"
